# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - name: Check repo
      run: ls
    - name: Install dependencies
      run:
        pip install flake8==3.6.0
    - name: Run Linting
      run: flake8
  unittesting:
    runs-on: ubuntu-latest
    strategy:
        matrix: 
          python: [2.7, 3.4, 3.5.4, 3.6]
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{matrix.python}}"
      - name: Installing Dependencies
        run:  python -m pip install --upgrade pip && pip install -r requirements/core.txt;pip install -r requirements/test.txt
      - name: Run unit tests
        run: pytest --cov=optimizely
    
